/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Controlador.UsuarioDAO;
import Modelo.Usuario;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author Santo Tomas
 */
public class VistaRegistro extends javax.swing.JPanel implements ActionListener {

    private UsuarioDAO usuarioDAO;
    
    // Declaramos el JPasswordField que DEBES añadir en el diseñador
    private javax.swing.JPasswordField txtContraseña;
    
    /**
     * Creates new form VistaRegistro
     */
    public VistaRegistro() {
        initComponents();
        
        // Inicializar el DAO
        this.usuarioDAO = new UsuarioDAO();
        
        // Añadir este panel como listener para el botón
        bttnRegistrar.addActionListener(this);
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == bttnRegistrar) {
            String nombres = txtNombres.getText();
            String apellidos = txtApellidos.getText();
            String rut = txtRut.getText();
            String correo = txtCorreo2.getText();
            
            // ASUMIENDO que añadiste 'txtContraseña' al diseñador
            // Si no lo hiciste, esta línea dará un NullPointerException
            String contraseña = new String(txtContraseña.getPassword()); 

            // Validación simple
            if (nombres.isEmpty() || apellidos.isEmpty() || rut.isEmpty() || correo.isEmpty() || contraseña.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Todos los campos (incluida contraseña) son obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // --- LÓGICA DE REGISTRO CON BASE DE DATOS ---
            
            // 1. Creamos el objeto Usuario
            Usuario nuevoUsuario = new Usuario(0, nombres, apellidos, rut, correo, "Cliente"); // Rol por defecto

            // 2. Llamamos al DAO para registrar
            boolean exito = usuarioDAO.registrarUsuario(nuevoUsuario, contraseña);

            if (exito) {
                JOptionPane.showMessageDialog(this, "Usuario " + nombres + " registrado exitosamente.", "Registro Completo", JOptionPane.INFORMATION_MESSAGE);
                limpiarCampos();
                // TODO: Aquí deberías navegar de vuelta al Login
            } else {
                JOptionPane.showMessageDialog(this, "Error al registrar el usuario. El correo o RUT podrían ya existir.", "Error de Registro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void limpiarCampos() {
        txtNombres.setText("");
        txtApellidos.setText("");
        txtRut.setText("");
        txtCorreo2.setText("");
        if (txtContraseña != null) {
            txtContraseña.setText("");
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombres = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblRut = new javax.swing.JLabel();
        lblCorreo2 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtRut = new javax.swing.JTextField();
        txtCorreo2 = new javax.swing.JTextField();
        bttnRegistrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblContraseña2 = new javax.swing.JLabel();
        txtContraseña2 = new javax.swing.JTextField();

        lblNombres.setText("Nombres:");

        lblApellidos.setText("Apellidos:");

        lblRut.setText("Rut:");

        lblCorreo2.setText("Correo:");

        bttnRegistrar.setText("Registrar");

        jLabel5.setText("Registro");

        lblContraseña2.setText("Contraseña:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(bttnRegistrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblContraseña2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtContraseña2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNombres)
                                        .addComponent(lblCorreo2)
                                        .addComponent(lblApellidos, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(lblRut))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCorreo2)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtApellidos)
                                                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombres)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidos)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRut)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCorreo2)
                    .addComponent(txtCorreo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContraseña2)
                    .addComponent(txtContraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(bttnRegistrar)
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnRegistrar;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblContraseña2;
    private javax.swing.JLabel lblCorreo2;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblRut;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtContraseña2;
    private javax.swing.JTextField txtCorreo2;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables
}
